/**
 * image_search.js  –  "Search by image" feature for the NSW Traffic Signs Catalogue.
 *
 * Dependencies (loaded lazily on first use):
 *   @xenova/transformers  via CDN — CLIP ViT-B/32 (~85 MB, cached after first load)
 *
 * Requires:
 *   SIGN_EMBEDDINGS  global — set by sign_embeddings.js (generated by embed_signs.py)
 *
 * Integration:
 *   1. Add to your HTML before </body>:
 *        <script src="sign_embeddings.js"></script>
 *        <script src="image_search.js"></script>
 *   2. The script looks for your existing search input and sign card container.
 *      Adjust the selectors in CONFIG below if needed.
 *   3. Call window.ImageSearch.init() after DOMContentLoaded, or let the script
 *      auto-initialise (it waits for DOMContentLoaded itself).
 */

(function (global) {
  "use strict";

  // ---------------------------------------------------------------------------
  // CONFIG — adjust selectors to match your HTML structure
  // ---------------------------------------------------------------------------
  const CONFIG = {
    // Selector for the container that holds all sign cards
    cardsContainer: "#signGrid",

    // Selector for individual sign cards (within cardsContainer)
    cardSelector: ".sign-card",

    // Attribute on each card that holds the sign's unique ID
    cardIdAttr: "data-sign-id",

    // Where to inject the image-search button (next to the search box)
    searchBarSelector: "#searchBar",

    // CDN for Transformers.js — pinned version for reproducibility
    transformersUrl:
      "https://cdn.jsdelivr.net/npm/@xenova/transformers@2.17.2/dist/transformers.min.js",

    // Number of top results to highlight
    topK: 5,

    // Cosine similarity threshold — results below this are hidden
    threshold: 0.18,
  };

  // ---------------------------------------------------------------------------
  // State
  // ---------------------------------------------------------------------------
  let _extractor = null;       // CLIP pipeline, loaded on demand
  let _modelLoading = false;
  let _modelReady = false;
  let _embeddings = null;      // decoded Float32Array map: { id -> Float32Array(512) }
  let _activeSearch = false;   // true while image-search results are shown

  // ---------------------------------------------------------------------------
  // Utility: base64 → Float32Array
  // ---------------------------------------------------------------------------
  function b64toFloat32(b64) {
    const bin = atob(b64);
    const buf = new ArrayBuffer(bin.length);
    const bytes = new Uint8Array(buf);
    for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
    return new Float32Array(buf);
  }

  // ---------------------------------------------------------------------------
  // Utility: cosine similarity between two Float32Arrays of equal length
  // ---------------------------------------------------------------------------
  function cosineSim(a, b) {
    let dot = 0, na = 0, nb = 0;
    for (let i = 0; i < a.length; i++) {
      dot += a[i] * b[i];
      na  += a[i] * a[i];
      nb  += b[i] * b[i];
    }
    // Both vectors are already L2-normalised from the Python script, so
    // na ≈ nb ≈ 1, but we guard against floating-point drift.
    return dot / (Math.sqrt(na) * Math.sqrt(nb) + 1e-8);
  }

  // ---------------------------------------------------------------------------
  // Decode SIGN_EMBEDDINGS once and cache
  // ---------------------------------------------------------------------------
  function getEmbeddings() {
    if (_embeddings) return _embeddings;
    if (typeof global.SIGN_EMBEDDINGS === "undefined") {
      throw new Error("SIGN_EMBEDDINGS not found. Make sure sign_embeddings.js is loaded first.");
    }
    _embeddings = {};
    for (const [id, b64] of Object.entries(global.SIGN_EMBEDDINGS)) {
      _embeddings[id] = b64toFloat32(b64);
    }
    return _embeddings;
  }

  // ---------------------------------------------------------------------------
  // Load Transformers.js + CLIP model lazily
  // ---------------------------------------------------------------------------
  async function loadModel(onProgress) {
    if (_modelReady) return _extractor;
    if (_modelLoading) {
      // Poll until ready rather than double-loading
      await new Promise((resolve) => {
        const t = setInterval(() => { if (_modelReady) { clearInterval(t); resolve(); } }, 200);
      });
      return _extractor;
    }

    _modelLoading = true;
    onProgress?.("Loading CLIP model…", 0);

    // Dynamic import from CDN
    const { pipeline, env } = await import(CONFIG.transformersUrl);

    // Cache models in browser IndexedDB (avoids re-download)
    env.cacheDir = "./.cache";
    env.allowRemoteModels = true;

    _extractor = await pipeline(
      "image-feature-extraction",
      "Xenova/clip-vit-base-patch32",
      {
        quantized: true,
        progress_callback: (prog) => {
          if (prog.status === "downloading" && prog.total) {
            const pct = Math.round((prog.loaded / prog.total) * 100);
            onProgress?.(`Downloading model… ${pct}%`, pct);
          } else if (prog.status === "loading") {
            onProgress?.("Loading model into memory…", 95);
          }
        },
      }
    );

    _modelReady = true;
    _modelLoading = false;
    onProgress?.("Model ready", 100);
    return _extractor;
  }

  // ---------------------------------------------------------------------------
  // Embed an image file → Float32Array(512)
  // ---------------------------------------------------------------------------
  async function embedImage(file, onProgress) {
    const extractor = await loadModel(onProgress);

    // Convert File to data URL
    const dataUrl = await new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => resolve(reader.result);
      reader.onerror = reject;
      reader.readAsDataURL(file);
    });

    onProgress?.("Computing embedding…", 98);
    const output = await extractor(dataUrl, { pooling: "mean", normalize: true });
    return new Float32Array(output.data);
  }

  // ---------------------------------------------------------------------------
  // Score all catalogue signs against a query embedding
  // ---------------------------------------------------------------------------
  function scoreAll(queryEmb) {
    const catalogue = getEmbeddings();
    const results = [];
    for (const [id, emb] of Object.entries(catalogue)) {
      results.push({ id, score: cosineSim(queryEmb, emb) });
    }
    results.sort((a, b) => b.score - a.score);
    return results;
  }

  // ---------------------------------------------------------------------------
  // Apply scores to the visible sign cards
  // ---------------------------------------------------------------------------
  function applyScores(scores) {
    const container = document.querySelector(CONFIG.cardsContainer);
    if (!container) {
      console.warn("ImageSearch: cards container not found. Adjust CONFIG.cardsContainer.");
      return;
    }

    const topResults = scores
      .filter((r) => r.score >= CONFIG.threshold)
      .slice(0, CONFIG.topK);
    const topIds = new Set(topResults.map((r) => String(r.id)));

    // Build id → card map and hide non-matches
    const cardMap = new Map();
    container.querySelectorAll(CONFIG.cardSelector).forEach((card) => {
      const id = card.getAttribute(CONFIG.cardIdAttr);
      cardMap.set(id, card);
      if (!topIds.has(id)) {
        card.style.display = "none";
        card.classList.remove("img-search-match");
        const badge = card.querySelector(".img-search-badge");
        if (badge) badge.remove();
      }
    });

    // Append top results in descending score order
    topResults.forEach(({ id, score }) => {
      const card = cardMap.get(String(id));
      if (!card) return;
      card.style.display = "";
      card.classList.add("img-search-match");
      if (getComputedStyle(card).position === "static") {
        card.style.position = "relative";
      }
      let badge = card.querySelector(".img-search-badge");
      if (!badge) {
        badge = document.createElement("div");
        badge.className = "img-search-badge";
        card.appendChild(badge);
      }
      const pct = Math.round(score * 100);
      badge.textContent = `${pct}% match`;
      badge.style.cssText = `
        position:absolute; top:6px; left:6px;
        background:rgba(30,120,255,0.88); color:#fff;
        font:bold 11px/1 system-ui,sans-serif;
        padding:3px 7px; border-radius:99px;
        pointer-events:none; z-index:10;
      `;
      container.appendChild(card);
    });
  }

  // ---------------------------------------------------------------------------
  // Clear image-search state and restore normal view
  // ---------------------------------------------------------------------------
  function clearImageSearch() {
    if (!_activeSearch) return;
    _activeSearch = false;

    const container = document.querySelector(CONFIG.cardsContainer);
    if (container) {
      container.querySelectorAll(CONFIG.cardSelector).forEach((card) => {
        card.style.display = "";
        card.classList.remove("img-search-match");
        const badge = card.querySelector(".img-search-badge");
        if (badge) badge.remove();
      });
    }

    // Remove the active pill from the button
    const btn = document.getElementById("img-search-btn");
    if (btn) {
      btn.classList.remove("active");
      btn.title = "Search by image";
    }

    // Destroy modal if open
    const modal = document.getElementById("img-search-modal");
    if (modal) modal.remove();
  }

  // ---------------------------------------------------------------------------
  // Build and show the upload modal
  // ---------------------------------------------------------------------------
  function showModal() {
    // Prevent duplicates
    if (document.getElementById("img-search-modal")) return;

    const modal = document.createElement("div");
    modal.id = "img-search-modal";
    modal.setAttribute("role", "dialog");
    modal.setAttribute("aria-modal", "true");
    modal.setAttribute("aria-label", "Search by image");
    modal.innerHTML = `
      <div id="img-search-backdrop"></div>
      <div id="img-search-panel">
        <button id="img-search-close" aria-label="Close">✕</button>
        <h2>Search by image</h2>
        <p class="img-search-hint">
          Upload a photo of a traffic sign to find the closest match in the catalogue.<br>
          <strong>Tip:</strong> crop or zoom to the sign before uploading for best results.
        </p>
        <label id="img-search-dropzone" for="img-search-input">
          <span id="img-search-dropzone-inner">
            <svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
              <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
              <polyline points="17 8 12 3 7 8"/>
              <line x1="12" y1="3" x2="12" y2="15"/>
            </svg>
            <span>Drop image here or <u>browse</u></span>
            <span style="font-size:12px;opacity:0.6">PNG, JPG, WEBP</span>
          </span>
          <img id="img-search-preview" alt="Preview" style="display:none">
        </label>
        <input id="img-search-input" type="file" accept="image/*" style="display:none">
        <div id="img-search-status" style="display:none">
          <div id="img-search-progress-bar"><div id="img-search-progress-fill"></div></div>
          <span id="img-search-status-text"></span>
        </div>
        <button id="img-search-go" disabled>Find matches</button>
      </div>
    `;

    // Styles — injected once
    if (!document.getElementById("img-search-styles")) {
      const style = document.createElement("style");
      style.id = "img-search-styles";
      style.textContent = `
        #img-search-backdrop {
          position:fixed; inset:0; background:rgba(0,0,0,.55);
          backdrop-filter:blur(3px); z-index:9998;
        }
        #img-search-panel {
          position:fixed; top:50%; left:50%; transform:translate(-50%,-50%);
          z-index:9999; background:var(--surface,#fff); color:var(--text,#111);
          border-radius:14px; padding:28px 28px 24px;
          width:min(460px, 94vw);
          box-shadow:0 8px 40px rgba(0,0,0,.25);
          border:1px solid var(--border,#e5e7eb);
          display:flex; flex-direction:column; gap:14px;
        }
        #img-search-panel h2 { margin:0; font-size:1.15rem; }
        .img-search-hint { margin:0; font-size:0.85rem; line-height:1.5; opacity:0.75; }
        #img-search-close {
          position:absolute; top:14px; right:16px;
          background:none; border:none; font-size:1.1rem;
          cursor:pointer; opacity:0.5; line-height:1;
          color:inherit;
        }
        #img-search-close:hover { opacity:1; }
        #img-search-dropzone {
          border:2px dashed currentColor; border-radius:10px;
          padding:24px 16px; cursor:pointer; text-align:center;
          opacity:0.65; transition:opacity .15s, border-color .15s;
          display:flex; align-items:center; justify-content:center;
          min-height:130px; position:relative; overflow:hidden;
        }
        #img-search-dropzone:hover, #img-search-dropzone.dragover {
          opacity:1; border-color:#1e78ff;
        }
        #img-search-dropzone-inner {
          display:flex; flex-direction:column; align-items:center; gap:8px;
          pointer-events:none;
        }
        #img-search-preview {
          max-width:100%; max-height:200px; border-radius:6px;
          object-fit:contain;
        }
        #img-search-status { display:flex; flex-direction:column; gap:6px; }
        #img-search-progress-bar {
          height:4px; background:rgba(128,128,128,.2); border-radius:99px;
          overflow:hidden;
        }
        #img-search-progress-fill {
          height:100%; background:#1e78ff; border-radius:99px;
          width:0; transition:width .3s;
        }
        #img-search-status-text { font-size:0.82rem; opacity:0.7; }
        #img-search-go {
          padding:10px 20px; border-radius:8px; border:none;
          background:#1e78ff; color:#fff; font-size:0.95rem;
          cursor:pointer; font-weight:600; transition:opacity .15s;
          align-self:flex-end;
        }
        #img-search-go:disabled { opacity:0.4; cursor:default; }
        #img-search-go:not(:disabled):hover { opacity:0.85; }
        #img-search-btn.active { outline:2px solid #1e78ff; }
      `;
      document.head.appendChild(style);
    }

    document.body.appendChild(modal);

    // Wire up events
    const input   = modal.querySelector("#img-search-input");
    const dropzone = modal.querySelector("#img-search-dropzone");
    const preview  = modal.querySelector("#img-search-preview");
    const inner    = modal.querySelector("#img-search-dropzone-inner");
    const goBtn    = modal.querySelector("#img-search-go");
    const statusEl = modal.querySelector("#img-search-status");
    const progFill = modal.querySelector("#img-search-progress-fill");
    const statusTxt= modal.querySelector("#img-search-status-text");
    const closeBtn = modal.querySelector("#img-search-close");
    const backdrop = modal.querySelector("#img-search-backdrop");

    let selectedFile = null;

    function setProgress(msg, pct) {
      statusEl.style.display = "flex";
      statusTxt.textContent = msg;
      progFill.style.width = `${pct}%`;
    }

    function setFile(file) {
      if (!file || !file.type.startsWith("image/")) return;
      selectedFile = file;
      const url = URL.createObjectURL(file);
      preview.src = url;
      preview.style.display = "block";
      inner.style.display = "none";
      goBtn.disabled = false;
    }

    input.addEventListener("change", () => setFile(input.files[0]));
    dropzone.addEventListener("dragover", (e) => { e.preventDefault(); dropzone.classList.add("dragover"); });
    dropzone.addEventListener("dragleave", () => dropzone.classList.remove("dragover"));
    dropzone.addEventListener("drop", (e) => {
      e.preventDefault();
      dropzone.classList.remove("dragover");
      setFile(e.dataTransfer.files[0]);
    });

    closeBtn.addEventListener("click", () => modal.remove());
    backdrop.addEventListener("click", () => modal.remove());

    document.addEventListener("keydown", function esc(e) {
      if (e.key === "Escape") { modal.remove(); document.removeEventListener("keydown", esc); }
    });

    goBtn.addEventListener("click", async () => {
      if (!selectedFile) return;
      goBtn.disabled = true;

      try {
        const queryEmb = await embedImage(selectedFile, (msg, pct) => setProgress(msg, pct));
        setProgress("Scoring catalogue…", 100);

        const scores = scoreAll(queryEmb);
        applyScores(scores);

        _activeSearch = true;
        const btn = document.getElementById("img-search-btn");
        if (btn) { btn.classList.add("active"); btn.title = "Clear image search"; }

        modal.remove();
      } catch (err) {
        console.error("ImageSearch error:", err);
        setProgress("Error: " + err.message, 0);
        goBtn.disabled = false;
      }
    });
  }

  // ---------------------------------------------------------------------------
  // Inject the camera button into the search bar
  // ---------------------------------------------------------------------------
  function injectButton() {
    if (document.getElementById("img-search-btn")) return;  // already injected

    const searchEl = document.querySelector(CONFIG.searchBarSelector);
    if (!searchEl) {
      console.warn("ImageSearch: search bar not found. Adjust CONFIG.searchBarSelector.");
      return;
    }

    const btn = document.createElement("button");
    btn.id = "img-search-btn";
    btn.type = "button";
    btn.title = "Search by image";
    btn.setAttribute("aria-label", "Search by image");
    btn.innerHTML = `
      <svg width="18" height="18" viewBox="0 0 24 24" fill="none"
           stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
        <rect x="3" y="3" width="18" height="18" rx="2" ry="2"/>
        <circle cx="8.5" cy="8.5" r="1.5"/>
        <polyline points="21 15 16 10 5 21"/>
      </svg>
    `;
    btn.style.cssText = `
      background:none; border:none; cursor:pointer; padding:4px 6px;
      display:inline-flex; align-items:center; vertical-align:middle;
      opacity:0.65; transition:opacity .15s; border-radius:6px;
      color:inherit;
    `;
    btn.addEventListener("mouseenter", () => { btn.style.opacity = "1"; });
    btn.addEventListener("mouseleave", () => { btn.style.opacity = btn.classList.contains("active") ? "1" : "0.65"; });

    btn.addEventListener("click", () => {
      if (_activeSearch) {
        clearImageSearch();
      } else {
        showModal();
      }
    });

    // Wrap the input and button together in a flex row, leaving the
    // parent section's column layout (label above, row below) intact
    const wrapper = document.createElement("div");
    wrapper.style.cssText = "display:flex; align-items:center; gap:4px;";
    searchEl.parentElement.insertBefore(wrapper, searchEl);
    wrapper.appendChild(searchEl);
    wrapper.appendChild(btn);
    searchEl.style.flex = "1";
    searchEl.style.minWidth = "0";
  }

  // ---------------------------------------------------------------------------
  // Public API
  // ---------------------------------------------------------------------------
  global.ImageSearch = {
    init: injectButton,
    clear: clearImageSearch,
    showModal,
  };

  // ---------------------------------------------------------------------------
  // Auto-initialise
  // ---------------------------------------------------------------------------
  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", injectButton);
  } else {
    injectButton();
  }

})(window);
